theme = "lucario"

# [adaptive-theme]
# light = "Tomorrow"
# dark = "synthwave"

cursor = 'â–‡'
editor = 'nvim'
blinking-cursor = true
option-as-alt = 'both'
# env-vars = []
# padding-x = 10
# use-fork = false
# working-dir = "/Users/zarkivy"
# ignore-selection-foreground-color = false

[window]
width = 1200
height = 800
mode = "Windowed"
foreground-opacity = 1.0
background-opacity = 0.8
blur = true
decorations = "Enabled"

[fonts]
size = 18
family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font"
# extras = [{ family = "Microsoft JhengHei" }]
# [fonts.regular]
# family = "cascadiamono"
# style = "normal"
# weight = 400
# [fonts.bold]
# family = "cascadiamono"
# style = "normal"
# weight = 800
# [fonts.italic]
# family = "cascadiamono"
# style = "italic"
# weight = 400
# [fonts.bold-italic]
# family = "cascadiamono"
# style = "italic"
# weight = 800

# Example:
[navigation]
mode = "CollapsedTab"
clickable = true
use-current-path = false
color-automation = [{ program = "ssh", color = "#199c4b" }]

# [scroll]
# multiplier = 3.0
# divider = 1.0

# [shell]
# program = "/bin/fish"
# args = ["--login"]
# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-c", "/var/www"]

# [colors]
# background = '#555a64'
# foreground = '#c5cdd9'
# cursor = '#f8f8f2'
# tabs = '#354157'
# tabs-active = '#ffffff'
#
# black = '#202023'
# blue = '#6cb6eb'
# cyan = '#5dbbc1'
# green = '#a0c980'
# magenta = '#d38aea'
# red = '#ec7279'
# white = '#f8f8f2'
# yellow = '#deb974'
#
# dim-foreground = '#dfdfd9'
# dim-black = '#000000'
# dim-blue = '#354157'
# dim-cyan = '#6fb3ca'
# dim-green = '#394634'
# dim-magenta = '#a176cc'
# dim-red = '#55393d'
# dim-white = '#758094'
# dim-yellow = '#E6A003'
#
# light-foreground = '#f8f8f2'
# light-black = '#535c6a'
# light-blue = '#d6accf'
# light-cyan = '#b9ecfd'
# light-green = '#72cc5a'
# light-magenta = '#d4a9ff'
# light-red = '#ff6541'
# light-white = '#ffffff'
# light-yellow = '#ffffa5'

# [bindings]
# keys = [
#   { key = "q", with = "super", action = "Quit" },
#   # Bytes[27, 91, 53, 126] is equivalent to "\x1b[5~"
#   { key = "home", with = "super | shift", bytes = [27, 91, 53, 126] }
# ]

# [renderer]
# performance = "High"
# backend = "Automatic"
# disable-renderer-when-unfocused = false

# [keyboard]
# use-kitty-keyboard-protocol = false
# disable-ctlseqs-alt = false

# [developer]
# log-level = "OFF"
